# Generated by Django 2.0.6 on 2018-06-28 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='total',
            field=models.FloatField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
