# Generated by Django 2.0.6 on 2018-06-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
