# Generated by Django 2.0.5 on 2018-07-03 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.CharField(max_length=100),
        ),
    ]
