# Generated by Django 2.0.6 on 2018-07-03 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_remove_detallecompra_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='compra',
            name='fecha',
        ),
    ]
