# Generated by Django 2.0.6 on 2018-06-28 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20180628_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='total',
            field=models.FloatField(max_length=100),
        ),
        migrations.AlterField(
            model_name='detallecompra',
            name='total',
            field=models.FloatField(default=0.0, max_length=100),
        ),
    ]
