# Generated by Django 2.0.6 on 2018-06-27 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventas',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='ventas',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='producto',
        ),
        migrations.DeleteModel(
            name='ventas',
        ),
    ]
