# Generated by Django 2.0.6 on 2018-06-28 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_auto_20180628_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecompra',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.proveedor'),
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='total',
            field=models.FloatField(default=0.0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateField(),
        ),
    ]
