# Generated by Django 2.0.5 on 2018-06-25 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_cliente_detalle_venta_venta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.Cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
