# Generated by Django 2.0.6 on 2018-06-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20180621_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
