# Generated by Django 2.0.5 on 2018-06-29 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20180628_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='venta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
