# Generated by Django 2.0.6 on 2018-07-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_remove_compra_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fecha',
            field=models.DateField(auto_now_add=True, default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallecompra',
            name='fecha',
            field=models.DateField(auto_now_add=True, default='1'),
            preserve_default=False,
        ),
    ]
