# Generated by Django 2.0.5 on 2018-06-25 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_auto_20180625_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='detalle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.detalle_venta'),
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='productos',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='productos',
            field=models.ManyToManyField(to='inventario.productos'),
        ),
    ]
