# Generated by Django 2.0.6 on 2018-06-26 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_auto_20180625_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_venta',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='detalle',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='venta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.venta'),
        ),
        migrations.AddField(
            model_name='venta',
            name='codigo',
            field=models.CharField(default='1', max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venta',
            name='productos',
            field=models.ManyToManyField(through='inventario.detalle_venta', to='inventario.productos'),
        ),
        migrations.RemoveField(
            model_name='detalle_venta',
            name='productos',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='productos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.productos'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
