# Generated by Django 2.0.6 on 2018-06-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_productos_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='stock',
            field=models.IntegerField(max_length=10000),
        ),
    ]
