# Generated by Django 2.0.5 on 2018-07-01 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_auto_20180629_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.CharField(default='2018/07/01', max_length=50),
        ),
    ]
