# Generated by Django 2.0.6 on 2018-06-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_productos_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
