# Generated by Django 2.0.5 on 2018-07-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_auto_20180702_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.IntegerField(max_length=10000),
        ),
    ]
