# Generated by Django 2.0.6 on 2018-06-22 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=70)),
                ('direccion', models.CharField(max_length=80)),
                ('registro', models.CharField(max_length=25)),
                ('telefono', models.CharField(max_length=12)),
            ],
        ),
    ]
